language: python

branches:
  only: master

notifications:
  webhooks: https://webhooks.gitter.im/e/af8b56ad2dd4ca61cb8e

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:$NUPIC
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: Lrb/OJ6iMQ34xyOTz53g3+B/OEZvOT26FVxOr1J8zqnZ11QPvJDO0zb8xd6A3FdDLGQh0NJOo3ZieN96BqSajYMVYeWVCR3qCReOIn3TwNNaD7UfuHoRPBkMQd7Th/EHNC4h0hurRjU7GYvjbFkSFpHlJ5yj3neBrvJspn4Hx5U=

install:
- echo $PYTHONPATH
- echo $NUPIC
- NUPIC_SHA=`cat nupic_sha.txt`
- 'echo NUPIC SHA: $NUPIC_SHA'

# These are required for the fetch_egg script.
- pip install requests
- pip install boto

# These are the required python dependencies for nupic.research
- pip install matplotlib

# If there is already a version of numpy installed at this point, remove it
# so there is no conflict with the one provided by nupic-linux64.
- pip uninstall numpy

# Fetches the binary distribution.
- python fetch_binary.py

# These are the required python dependencies for NuPIC
- git clone https://github.com/numenta/nupic-linux64.git --depth=50
- source nupic-linux64/bin/activate
- export NTA_CONF_PATH=/usr/local

# Unpacks the distro into the Travis-CI file system
- sudo tar zxvf nupic-archive.tar.gz -C /

- export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/dist-packages

# Install nupic.research/sensorimotor
- cd ${TRAVIS_BUILD_DIR}/sensorimotor
- python setup.py install

script:
# Run sensorimotor tests
- py.test tests/
