language: python

branches:
  only: master

notifications:
  webhooks: https://webhooks.gitter.im/e/af8b56ad2dd4ca61cb8e

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:$NUPIC
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: Lrb/OJ6iMQ34xyOTz53g3+B/OEZvOT26FVxOr1J8zqnZ11QPvJDO0zb8xd6A3FdDLGQh0NJOo3ZieN96BqSajYMVYeWVCR3qCReOIn3TwNNaD7UfuHoRPBkMQd7Th/EHNC4h0hurRjU7GYvjbFkSFpHlJ5yj3neBrvJspn4Hx5U=

before_install:
  # Upgrade pip
  - pip install --upgrade pip

  # Wheels is currently used for installation.
  - pip install wheel

  # These are required for the fetch_egg script.
  - pip install requests
  - pip install boto

  # These are the required python dependencies for nupic.research
  - pip install numpy --upgrade
  - pip install matplotlib


install:
  - echo $PYTHONPATH
  - echo $NUPIC
  - NUPIC_SHA=`cat nupic_sha.txt`
  - 'echo NUPIC SHA: $NUPIC_SHA'


  # Fetches the NuPIC wheels.
  - python fetch_wheels.py

  # Install wheels we just downloaded.
  - NUPIC_VERSION=`ls ./wheelhouse | grep nupic | cut -d'-' -f2`
  - echo "Installing NuPIC ${NUPIC_VERSION} with wheels..."
  - pip install --use-wheel --no-index --find-links=wheelhouse nupic==${NUPIC_VERSION}

  # Install nupic.research/sensorimotor
  - cd ${TRAVIS_BUILD_DIR}/sensorimotor
  - python setup.py install

script:
  # Run sensorimotor tests
  - py.test tests/
